version: "3"
services:
    timescaledb:
        container_name: timescaledb
        image: timescale/timescaledb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: iot_mqtt_test
    mqtt-broker-sub:
        container_name: mqtt-broker-sub
        image: emqx/emqx
        ports:
            - "1883:1883"
    subscriber:
        depends_on: 
            - timescaledb
            - mqtt-broker-sub
        container_name: subscriber
        restart: always
        build: 
            dockerfile: Dockerfile
            context: .
        command: bash -c "python /app/create_db_setup.py && python /app/subscriber.py"
        links:
            - timescaledb
            - mqtt-broker-sub
